services: docker
script:
  - docker build -t "adamb70/redis-overcommit-thp-on-host:latest" .
before_deploy:
  # Extract the version components out of a `v12.34.56` or `12.34.56` version string
  - IFS=. read MAJOR MINOR PATCH <<< "${TRAVIS_TAG#v}"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push "adamb70/redis-overcommit-thp-on-host:latest" && docker tag "adamb70/redis-overcommit-thp-on-host:latest" "adamb70/redis-overcommit-thp-on-host:${MAJOR}" && docker push "adamb70/redis-overcommit-thp-on-host:${MAJOR}" && docker tag "adamb70/redis-overcommit-thp-on-host:latest" "adamb70/redis-overcommit-thp-on-host:${MAJOR}.${MINOR}" && docker push "adamb70/redis-overcommit-thp-on-host:${MAJOR}.${MINOR}" && docker tag "adamb70/redis-overcommit-thp-on-host:latest" "adamb70/redis-overcommit-thp-on-host:${MAJOR}.${MINOR}.${PATCH}" && docker push "adamb70/redis-overcommit-thp-on-host:${MAJOR}.${MINOR}.${PATCH}"
  skip_cleanup: false
  on:
    tags: true
